# Open a dump file created by MLT dumper and
# Remove duplicates, translate into any language
# with google translate

# pip3 install unidecode

from unidecode import unidecode
import os

# Any special characters will be converted
# Into @ (ascii 64).
f = open("dump", "rb")
contents = bytearray(f.read())
for i in range(len(contents)):
    if contents[i] > 127:
        contents[i] = 64

lines = contents.decode("ascii").split("\n")

removeDuplicates = sorted(list(set(lines)))

# "input" is expected to have same lines as output,
# but translated into another language
o = open("output", "w")
i = open("input", "r")
inputText = i.read().split("\n")

o.write("# Auto generated by MLT extract.py\n")
o.write("# GPL 2, By Daniel C\n")

k = 0
for i in removeDuplicates:
    if i == '' or "@" in i or i == ' ':
        continue
    # Generating input
    #o.write(i + "\n")
    #continue

    if unidecode(inputText[k]) == i:
        k += 1
        continue

    x = i + "|" + unidecode(inputText[k])
    o.write(x + "\n")
    k += 1
o.close()

